### ISSUE TITLE
Why do you do open source?

### ISSUE THREAD

**Issue by sindresorhus** [hughsk/ama#1]

**Comment by nickdesaulniers** [comment]
the answer should go here: https://github.com/nickdesaulniers/What-Open-Source-Means-To-Me ;) :rocket: :guitar:

**Comment by hughsk** [comment]
A few reasons :)

1. When I started out late 2011 I was looking for a combination of feedback and promotion, effectively so I could improve my skills and find new clients.
1. Late 2012 I got quite sick and was mostly housebound for a while. I got involved with the [voxel.js](http://voxeljs.com) project as a way to keep motivated in my spare time. I had a nice routine where I'd spend my weekends working out a new concept, building it out, releasing it and getting feedback from people. That was probably the first time I got involved with a community project rather than just writing stuff for my own bubble of packages.
1. After a while it became about practicality for myself and others. The amount of code that gets rewritten for each project is still huge, so releasing those tidbits as tiny modules saves everybody a little bit of time. Some of the trickier stuff can be really rewarding in that respect since you can push the ecosystem forward rather than holding it back for the sake of competition.
1. [stack.gl](http://stack.gl/), for me, has all been about minimising the barrier to entry to picking up intermediate/advanced graphics programming concepts. It's not as easy as three.js for sure, but having the pieces isolated means that it's a lot easier to pull stuff out and use in your own project. 3D was super scary and mysterious for me for a long time, but I don't think it has to be and would like to see that change for others in the future.
