### ISSUE TITLE
What is the the most frustrating technological limit on your ambitions as a creator?

### ISSUE THREAD

**Issue by colingourlay** [hughsk/ama#8]

**Comment by hughsk** [comment]
Time? In terms of technological limits, performance is certainly a big one. The challenge is nice, but I would really love to be able to work on visual stuff without having to worry about that. More importantly:

[<img width="655" alt="screenshot_2015-07-09_9 48 12 pm" src="https://cloud.githubusercontent.com/assets/569817/8605254/4f12da32-2684-11e5-88c6-8ccc37684eb9.png">](https://twitter.com/chriscoyier/status/617726577724403712)

...*ducks*

It's probably the most obvious, but cross-device compatability is easily my number one frustration – I've discovered it's even more of a nightmare with WebGL because there's a bunch of driver-specific bugs that you can only test/debug if you've got the physical machine there with you.

On a personal level I'm not super enthralled about supporting a plethora of devices, alas it's my job to do so and the approachability of web-based projects is great. It definitely holds my commercial projects back though and I can't help but get grumpy from time to time seeing stuff like this:

<img width="601" alt="screenshot_2015-07-09_10 11 23 pm" src="https://cloud.githubusercontent.com/assets/569817/8605729/82137bbe-2687-11e5-9840-fe34aa0abce4.png">

<img width="649" alt="screenshot_2015-06-26_3 50 47 pm" src="https://cloud.githubusercontent.com/assets/569817/8605349/07919e72-2685-11e5-88a5-30d8b48add8e.png">

([ENOUGH](http://cabbi.bo/enough/) is a friend's personal project and took over a year of spare time to make, works on Chrome/Firefox. It's also super amazing.)
